# Generated by Django 3.0.3 on 2020-04-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource_accounting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.IntegerField()),
                ('name', models.CharField(max_length=5)),
                ('amount', models.FloatField()),
                ('type_measure', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('cost', models.CharField(max_length=20)),
                ('data', models.DateField()),
            ],
        ),
    ]
