# Generated by Django 3.0.3 on 2020-04-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_accounting', '0002_auto_20200420_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource_accounting',
            name='ID',
        ),
        migrations.AlterField(
            model_name='resource_accounting',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
