# Generated by Django 3.0.3 on 2020-04-20 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource_accounting', '0003_auto_20200420_2110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource_accounting',
            old_name='name',
            new_name='title',
        ),
    ]
