# Generated by Django 3.0.3 on 2020-04-20 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource_accounting', '0004_auto_20200420_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource_accounting',
            name='cost',
        ),
    ]
