# Generated by Django 3.0.3 on 2020-04-21 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource_accounting', '0006_auto_20200420_2247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource_accounting',
            old_name='data',
            new_name='date',
        ),
    ]
